env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
  '@typescript-eslint/require-array-sort-compare':
    - 'off'
  '@typescript-eslint/no-non-null-assertion':
    - 'off'
  '@typescript-eslint/no-unused-vars':
    - warn
